language: cpp
sudo: required
services: 
  - docker
dist: focal
compiler:
  - clang

before_install:
  - docker build -t y9luiz/face-recognition-server  .
script:
  - docker run  y9luiz/face-recognition-server scripts/run_tests.sh