language: cpp
os:
  - linux
  - windows

services: 
  - docker
dist: focal
compiler:
  - clang

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker build -t y9luiz/face-recognition-server  -f "Dockerfile" . ;  fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker build -t y9luiz/face-recognition-server  -f "Dockerfile.CodeCoverage" . ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then  
      powershell -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
      powershell ./scripts/build_windows.ps1 ;
    fi

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker run  y9luiz/face-recognition-server scripts/run_tests.sh ; fi