language: cpp
os:
  - linux
  - windows

services: 
  - docker
dist: focal
compiler:
  - clang

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker build -t y9luiz/face-recognition-server  -f "Dockerfile" . ;  fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker build -t y9luiz/face-recognition-server  -f "Dockerfile.CodeCoverage" . ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then  PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned' ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then PowerShell ./scripts/build_windows.ps1 ; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker run  y9luiz/face-recognition-server scripts/run_tests.sh ; fi