from ubuntu:20.04

LABEL maintainer="y9luiz"

RUN apt-get update
RUN apt-get install -y clang
RUN apt-get install -y llvm
RUN apt-get install -y cmake
RUN apt-get install -y libboost-dev
RUN apt-get install -y libboost-system-dev
RUN apt-get install -y libboost-date-time-dev
RUN apt-get install -y ninja-build

RUN mkdir /home/faceRecognitionServer

WORKDIR /home/faceRecognitionServer

COPY . .

RUN bash scripts/build_coverage.sh