from ubuntu:20.04

LABEL maintainer="y9luiz"

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Moscow

RUN apt-get update
RUN apt-get install -y cmake \
    build-essential \
    libboost-dev \
    libboost-system-dev \
    libboost-date-time-dev \
    ninja-build \
    lcov

RUN mkdir /home/faceRecognitionServer

WORKDIR /home/faceRecognitionServer

COPY . .

RUN bash scripts/build_coverage.sh