from dkimg/opencv:4.5.5-ubuntu

LABEL maintainer="y9luiz"

RUN apt-get update && apt-get install -y \
    clang \
    cmake \
    libboost-dev \
    libboost-system-dev \
    libboost-date-time-dev \
    ninja-build \
    llvm

RUN mkdir /home/faceRecognitionServer

WORKDIR /home/faceRecognitionServer

COPY . .

RUN bash scripts/build_coverage.sh