name: Manual Build MS Windows

on:
  workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Manual Build on Windows
      run:  PowerShell ./scripts/build_windows.ps1
