name: Build ubuntu 20-04 Code Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build ubuntu 20-04 Code Coverage
      run: |
           export IMAGE_NAME=face-recongition-server-code-coverage-ubuntu-20.04:$(date +%s)
           docker build . --file Dockerfile --tag $IMAGE_NAME
           docker run --user $UID -v $(pwd)/report:/faceRecognitionServer/build_coverage/report \
           --rm $IMAGE_NAME bash scripts/build_coverage.sh
           chmod -R 777 ./report

    - uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ./report/

    - uses: actions/download-artifact@v3
      with:
        name: code-coverage-report
        path: ./report/
    - name: Display structure of downloaded files
      run: ls -R	
      working-directory: ./report/
