name: Build ubuntu 20-04 Code Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build ubuntu 20-04 Code Coverage
      run: docker build . --file Dockerfile.CodeCoverage --tag my-image-name:$(date +%s)
    - uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: /home/faceRecognitionServer/build_coverage/report/

    - uses: actions/download-artifact@v3
      with:
        name: code-coverage-report
        path: /home/faceRecognitionServer/build_coverage/report/
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: /home/faceRecognitionServer/build_coverage/report/
