name: Build ubuntu 20-04 Code Coverage

on:
  workflow_dispatch
  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build ubuntu 20-04 Code Coverage
      run: docker build . --file Dockerfile.CodeCoverage --tag my-image-name:$(date +%s)
