name: Build ubuntu 20-04 Debug

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build ubuntu 20-04 Debug
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
