name: Build ubuntu 20-04 Code Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build ubuntu 20-04 Code Coverage
      run: |
           export IMAGE_NAME=face-recongition-server-code-coverage-ubuntu-20.04:$(date +%s)
           docker build . --build-arg UID=$(id -u) --file Dockerfile --tag $IMAGE_NAME
           docker run -v $(pwd)/report:/report \
           --rm $IMAGE_NAME bash scripts/build_coverage.sh
           mv ./build_coverage/report /report
           chmod -R 777 /report

    - uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: /report/

    - uses: actions/download-artifact@v3
      with:
        name: code-coverage-report
        path: /report/
    - name: Display structure of downloaded files
      run: ls -R	
      working-directory: /report/
